// <auto-generated />
namespace Connecting.To.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "202005042109442_edit-employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
